// Centralizzata configurazione di tutti i provider video

export type VideoProviderType = 
  | 'auto'
  | 'google-veo'
  // AI/ML API - Runway
  | 'aiml-runway-gen3-turbo'
  | 'aiml-runway-gen4-turbo'
  | 'aiml-runway-gen4-aleph'
  | 'aiml-runway-act-two'
  // AI/ML API - Kling
  | 'aiml-kling-v1-std'
  | 'aiml-kling-v1-pro'
  | 'aiml-kling-v1.6-std'
  | 'aiml-kling-v1.6-pro'
  | 'aiml-kling-v1.6-pro-effects'
  | 'aiml-kling-v1.6-multi-i2v'
  | 'aiml-kling-v2-master'
  | 'aiml-kling-v2.1-std'
  | 'aiml-kling-v2.1-pro'
  | 'aiml-kling-v2.1-master'
  | 'aiml-kling-v2.5-turbo-pro'
  | 'aiml-kling-v2.6-pro'
  | 'aiml-kling-o1'
  // AI/ML API - Luma
  | 'aiml-luma-ray-1.6'
  | 'aiml-luma-ray-2'
  | 'aiml-luma-ray-flash-2'
  // AI/ML API - Sora (OpenAI)
  | 'aiml-sora-2-t2v'
  | 'aiml-sora-2-i2v'
  | 'aiml-sora-2-pro-t2v'
  | 'aiml-sora-2-pro-i2v'
  // AI/ML API - MiniMax
  | 'aiml-minimax-video-01'
  | 'aiml-minimax-hailuo-02'
  | 'aiml-minimax-hailuo-2.3'
  | 'aiml-minimax-hailuo-2.3-fast'
  // AI/ML API - PixVerse
  | 'aiml-pixverse-v5-t2v'
  | 'aiml-pixverse-v5-i2v'
  | 'aiml-pixverse-v5-transition'
  | 'aiml-pixverse-v5.5-t2v'
  | 'aiml-pixverse-v5.5-i2v'
  // AI/ML API - Google Veo
  | 'aiml-veo2-t2v'
  | 'aiml-veo2-i2v'
  | 'aiml-veo3'
  | 'aiml-veo3-i2v'
  | 'aiml-veo3-fast'
  | 'aiml-veo3-i2v-fast'
  | 'aiml-veo3.1-t2v'
  | 'aiml-veo3.1-i2v'
  | 'aiml-veo3.1-t2v-fast'
  | 'aiml-veo3.1-i2v-fast'
  | 'aiml-veo3.1-ref-to-video'
  | 'aiml-veo3.1-first-last-i2v'
  // AI/ML API - Alibaba Wan
  | 'aiml-wan-2.1-t2v'
  | 'aiml-wan-2.1-i2v'
  | 'aiml-wan-2.5-t2v'
  | 'aiml-wan-2.6-t2v'
  | 'aiml-wan-2.6-i2v'
  | 'aiml-wan-2.6-r2v'
  // AI/ML API - ByteDance Seedance
  | 'aiml-seedance-lite-t2v'
  | 'aiml-seedance-lite-i2v'
  | 'aiml-seedance-pro-t2v'
  | 'aiml-seedance-pro-i2v'
  | 'aiml-omnihuman'
  | 'aiml-omnihuman-1.5'
  // AI/ML API - Krea
  | 'aiml-krea-wan-14b-t2v'
  | 'aiml-krea-wan-14b-v2v'
  // AI/ML API - Kandinsky
  | 'aiml-kandinsky5-t2v'
  | 'aiml-kandinsky5-distill-t2v'
  // AI/ML API - VEED Fabric
  | 'aiml-veed-fabric-1.0'
  | 'aiml-veed-fabric-1.0-fast'
  // Vidu
  | 'vidu-q3-turbo-t2v'
  | 'vidu-q3-turbo-i2v'
  | 'vidu-q3-pro-t2v'
  | 'vidu-q3-pro-i2v'
  | 'vidu-q2-t2v'
  | 'vidu-q2-i2v'
  | 'vidu-q1-t2v'
  | 'vidu-q1-i2v'
  // PiAPI providers
  | 'piapi-kling-2.1'
  | 'piapi-kling-2.5'
  | 'piapi-kling-2.6'
  | 'piapi-hailuo'
  | 'piapi-luma'
  | 'piapi-wan'
  | 'piapi-hunyuan'
  | 'piapi-skyreels'
  | 'piapi-framepack'
  | 'piapi-veo3'
  | 'piapi-sora2'
  // Freepik
  | 'freepik';

export type ProviderGroup = 'google' | 'aiml' | 'piapi' | 'freepik' | 'vidu' | 'auto';

export interface VideoProviderInfo {
  id: VideoProviderType;
  name: string;
  shortName: string;
  group: ProviderGroup;
  description: string;
  color: string; // Tailwind class
  badgeColor: string; // Tailwind bg class for badge
  textColor: string; // Tailwind text class for badge
  speed: 1 | 2 | 3; // 1=lento, 2=medio, 3=veloce
  quality: 1 | 2 | 3; // 1=base, 2=buona, 3=eccellente
  cost: 1 | 2 | 3; // 1=economico, 2=medio, 3=costoso
  features: string[];
  estimatedTime: string;
  fallbackOrder: VideoProviderType[];
  durations: { value: string; label: string }[];
  resolutions: { value: string; label: string }[];
  aspectRatios?: { value: string; label: string }[];
  supportsAudio?: boolean;
  supportsImageToVideo?: boolean;
  supportsTextToVideo?: boolean;
  supportsEndFrame?: boolean; // Supports end frame for interpolation (e.g., Framepack)
  requiresApiKey?: string; // Nome del secret richiesto
  modelId?: string; // ID modello per API
  category?: string; // Categoria per raggruppamento UI
}

// Modello base per AI/ML API providers
const aimlBaseConfig = {
  group: 'aiml' as ProviderGroup,
  color: 'bg-purple-500',
  badgeColor: 'bg-purple-500/20',
  textColor: 'text-purple-500',
  requiresApiKey: 'AIML_API_KEY',
};

export const VIDEO_PROVIDERS: Record<VideoProviderType, VideoProviderInfo> = {
  auto: {
    id: 'auto',
    name: 'Automatico',
    shortName: 'Auto',
    group: 'auto',
    description: 'Selezione automatica del provider migliore',
    color: 'bg-accent',
    badgeColor: 'bg-accent/20',
    textColor: 'text-accent',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Selezione automatica', 'Fallback auto'],
    estimatedTime: '2-5 min',
    fallbackOrder: ['google-veo', 'aiml-veo3.1-t2v', 'piapi-kling-2.5'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
  },
  'google-veo': {
    id: 'google-veo',
    name: 'Google Veo 3.1 (Diretto)',
    shortName: 'Veo Diretto',
    group: 'google',
    description: 'API Diretta Google, audio nativo integrato',
    color: 'bg-blue-500',
    badgeColor: 'bg-blue-500/20',
    textColor: 'text-blue-500',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['API Diretta', 'Audio nativo', 'Alta qualità'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-veo3.1-t2v', 'piapi-kling-2.5'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    requiresApiKey: 'GOOGLE_AI_API_KEY',
  },

  // ============ AI/ML API - RUNWAY ============
  'aiml-runway-gen3-turbo': {
    ...aimlBaseConfig,
    id: 'aiml-runway-gen3-turbo',
    name: 'AI/ML: Runway Gen-3 Turbo',
    shortName: 'Gen-3 Turbo',
    description: 'Gen-3 Alpha Turbo, veloce e alta qualità',
    speed: 3,
    quality: 3,
    cost: 2,
    features: ['Turbo speed', 'Alta qualità', 'T2V + I2V'],
    estimatedTime: '1-3 min',
    fallbackOrder: ['aiml-runway-gen4-turbo', 'aiml-kling-v2.6-pro'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'gen3a_turbo',
    category: 'Runway',
  },
  'aiml-runway-gen4-turbo': {
    ...aimlBaseConfig,
    id: 'aiml-runway-gen4-turbo',
    name: 'AI/ML: Runway Gen-4 Turbo',
    shortName: 'Gen-4 Turbo',
    description: 'Ultima generazione Runway, massima qualità',
    color: 'bg-purple-600',
    badgeColor: 'bg-purple-600/20',
    textColor: 'text-purple-600',
    speed: 2,
    quality: 3,
    cost: 3,
    features: ['Ultima generazione', 'Qualità premium', 'T2V + I2V'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-runway-gen3-turbo', 'aiml-kling-v2.6-pro'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'runway/gen4_turbo',
    category: 'Runway',
  },
  'aiml-runway-gen4-aleph': {
    ...aimlBaseConfig,
    id: 'aiml-runway-gen4-aleph',
    name: 'AI/ML: Runway Aleph',
    shortName: 'Aleph',
    description: 'Modello Aleph per effetti avanzati',
    color: 'bg-purple-700',
    badgeColor: 'bg-purple-700/20',
    textColor: 'text-purple-700',
    speed: 2,
    quality: 3,
    cost: 3,
    features: ['Effetti avanzati', 'Qualità cinematica'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-runway-gen4-turbo', 'aiml-runway-gen3-turbo'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'runway/gen4_aleph',
    category: 'Runway',
  },
  'aiml-runway-act-two': {
    ...aimlBaseConfig,
    id: 'aiml-runway-act-two',
    name: 'AI/ML: Runway Act Two',
    shortName: 'Act Two',
    description: 'Performance e acting realistici',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Acting realistico', 'Personaggi'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-runway-gen4-turbo', 'aiml-kling-v2.6-pro'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'runway/act_two',
    category: 'Runway',
  },

  // ============ AI/ML API - KLING ============
  'aiml-kling-v1-std': {
    ...aimlBaseConfig,
    id: 'aiml-kling-v1-std',
    name: 'AI/ML: Kling v1 Standard',
    shortName: 'Kling v1 Std',
    description: 'Versione base economica',
    color: 'bg-purple-400',
    badgeColor: 'bg-purple-400/20',
    textColor: 'text-purple-400',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['Economico', 'Base'],
    estimatedTime: '2-3 min',
    fallbackOrder: ['aiml-kling-v1-pro', 'aiml-kling-v1.6-std'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'kling-video/v1/standard/text-to-video',
    category: 'Kling',
  },
  'aiml-kling-v1-pro': {
    ...aimlBaseConfig,
    id: 'aiml-kling-v1-pro',
    name: 'AI/ML: Kling v1 Pro',
    shortName: 'Kling v1 Pro',
    description: 'Versione Pro con qualità superiore',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Qualità Pro', 'Dettagli migliori'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-kling-v1.6-pro', 'aiml-kling-v2-master'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'kling-video/v1/pro/text-to-video',
    category: 'Kling',
  },
  'aiml-kling-v1.6-std': {
    ...aimlBaseConfig,
    id: 'aiml-kling-v1.6-std',
    name: 'AI/ML: Kling v1.6 Standard',
    shortName: 'Kling 1.6 Std',
    description: 'Versione 1.6 standard bilanciata',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['Bilanciato', 'Buon Q/P'],
    estimatedTime: '2-3 min',
    fallbackOrder: ['aiml-kling-v1.6-pro', 'aiml-kling-v2-master'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'kling-video/v1.6/standard/text-to-video',
    category: 'Kling',
  },
  'aiml-kling-v1.6-pro': {
    ...aimlBaseConfig,
    id: 'aiml-kling-v1.6-pro',
    name: 'AI/ML: Kling v1.6 Pro',
    shortName: 'Kling 1.6 Pro',
    description: 'Versione 1.6 Pro, ottima qualità',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Pro quality', 'Transizioni fluide'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-kling-v2-master', 'aiml-kling-v2.1-pro'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'kling-video/v1.6/pro/text-to-video',
    category: 'Kling',
  },
  'aiml-kling-v1.6-pro-effects': {
    ...aimlBaseConfig,
    id: 'aiml-kling-v1.6-pro-effects',
    name: 'AI/ML: Kling v1.6 Pro Effects',
    shortName: 'Kling Effects',
    description: 'Effetti speciali avanzati',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Effetti speciali', 'VFX'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-kling-v1.6-pro', 'aiml-kling-v2.6-pro'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'klingai/kling-video-v1.6-pro-effects',
    category: 'Kling',
  },
  'aiml-kling-v1.6-multi-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-kling-v1.6-multi-i2v',
    name: 'AI/ML: Kling v1.6 Multi-Image',
    shortName: 'Kling Multi-I2V',
    description: 'Video da multiple immagini',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Multi-immagine', 'Storyboard'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-kling-v1.6-pro', 'aiml-veo3.1-first-last-i2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'kling-video/v1.6/standard/multi-image-to-video',
    category: 'Kling',
  },
  'aiml-kling-v2-master': {
    ...aimlBaseConfig,
    id: 'aiml-kling-v2-master',
    name: 'AI/ML: Kling v2.0 Master',
    shortName: 'Kling 2.0',
    description: 'Versione 2.0 Master, alta qualità',
    color: 'bg-purple-600',
    badgeColor: 'bg-purple-600/20',
    textColor: 'text-purple-600',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Master quality', 'Dettagli HD'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-kling-v2.1-master', 'aiml-kling-v2.6-pro'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'klingai/v2-master-text-to-video',
    category: 'Kling',
  },
  'aiml-kling-v2.1-std': {
    ...aimlBaseConfig,
    id: 'aiml-kling-v2.1-std',
    name: 'AI/ML: Kling v2.1 Standard',
    shortName: 'Kling 2.1 Std',
    description: 'Versione 2.1 standard',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['Standard', 'Economico'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-kling-v2.1-pro', 'aiml-kling-v2.1-master'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'kling-video/v2.1/standard/image-to-video',
    category: 'Kling',
  },
  'aiml-kling-v2.1-pro': {
    ...aimlBaseConfig,
    id: 'aiml-kling-v2.1-pro',
    name: 'AI/ML: Kling v2.1 Pro',
    shortName: 'Kling 2.1 Pro',
    description: 'Versione 2.1 Pro, qualità superiore',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Pro quality', 'Migliore I2V'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-kling-v2.1-master', 'aiml-kling-v2.6-pro'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'kling-video/v2.1/pro/image-to-video',
    category: 'Kling',
  },
  'aiml-kling-v2.1-master': {
    ...aimlBaseConfig,
    id: 'aiml-kling-v2.1-master',
    name: 'AI/ML: Kling v2.1 Master',
    shortName: 'Kling 2.1 Master',
    description: 'Versione 2.1 Master, massima qualità',
    color: 'bg-purple-600',
    badgeColor: 'bg-purple-600/20',
    textColor: 'text-purple-600',
    speed: 2,
    quality: 3,
    cost: 3,
    features: ['Master quality', 'Premium'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-kling-v2.6-pro', 'aiml-kling-v2.5-turbo-pro'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'klingai/v2.1-master-text-to-video',
    category: 'Kling',
  },
  'aiml-kling-v2.5-turbo-pro': {
    ...aimlBaseConfig,
    id: 'aiml-kling-v2.5-turbo-pro',
    name: 'AI/ML: Kling v2.5 Turbo Pro',
    shortName: 'Kling 2.5 Turbo',
    description: 'Veloce con qualità Pro',
    color: 'bg-purple-500',
    badgeColor: 'bg-purple-500/20',
    textColor: 'text-purple-500',
    speed: 3,
    quality: 3,
    cost: 2,
    features: ['Turbo speed', 'Pro quality'],
    estimatedTime: '1-3 min',
    fallbackOrder: ['aiml-kling-v2.6-pro', 'aiml-kling-v2.1-master'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'klingai/v2.5-turbo/pro/text-to-video',
    category: 'Kling',
  },
  'aiml-kling-v2.6-pro': {
    ...aimlBaseConfig,
    id: 'aiml-kling-v2.6-pro',
    name: 'AI/ML: Kling v2.6 Pro',
    shortName: 'Kling 2.6 Pro',
    description: 'Ultimo modello Kling, massima qualità',
    color: 'bg-purple-700',
    badgeColor: 'bg-purple-700/20',
    textColor: 'text-purple-700',
    speed: 2,
    quality: 3,
    cost: 3,
    features: ['Ultimo modello', 'Premium quality'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-kling-v2.5-turbo-pro', 'aiml-kling-v2.1-master'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'klingai/video-v2-6-pro-text-to-video',
    category: 'Kling',
  },
  'aiml-kling-o1': {
    ...aimlBaseConfig,
    id: 'aiml-kling-o1',
    name: 'AI/ML: Kling O1',
    shortName: 'Kling O1',
    description: 'Modello O1 avanzato con reference',
    color: 'bg-purple-800',
    badgeColor: 'bg-purple-800/20',
    textColor: 'text-purple-800',
    speed: 1,
    quality: 3,
    cost: 3,
    features: ['O1 avanzato', 'Reference-to-video', 'V2V'],
    estimatedTime: '5-8 min',
    fallbackOrder: ['aiml-kling-v2.6-pro', 'aiml-veo3.1-ref-to-video'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'klingai/video-o1-image-to-video',
    category: 'Kling',
  },

  // ============ AI/ML API - LUMA ============
  'aiml-luma-ray-1.6': {
    ...aimlBaseConfig,
    id: 'aiml-luma-ray-1.6',
    name: 'AI/ML: Luma Ray 1.6',
    shortName: 'Ray 1.6',
    description: 'Stile cinematico unico',
    color: 'bg-cyan-500',
    badgeColor: 'bg-cyan-500/20',
    textColor: 'text-cyan-500',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Cinematico', 'Stile unico'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-luma-ray-2', 'aiml-luma-ray-flash-2'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'luma/ray-1.6',
    category: 'Luma',
  },
  'aiml-luma-ray-2': {
    ...aimlBaseConfig,
    id: 'aiml-luma-ray-2',
    name: 'AI/ML: Luma Ray 2',
    shortName: 'Ray 2',
    description: 'Nuova generazione Luma, qualità premium',
    color: 'bg-cyan-600',
    badgeColor: 'bg-cyan-600/20',
    textColor: 'text-cyan-600',
    speed: 2,
    quality: 3,
    cost: 3,
    features: ['Ray 2', 'Premium quality'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-luma-ray-1.6', 'aiml-luma-ray-flash-2'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'luma/ray-2',
    category: 'Luma',
  },
  'aiml-luma-ray-flash-2': {
    ...aimlBaseConfig,
    id: 'aiml-luma-ray-flash-2',
    name: 'AI/ML: Luma Ray Flash 2',
    shortName: 'Ray Flash 2',
    description: 'Versione veloce di Ray 2',
    color: 'bg-cyan-400',
    badgeColor: 'bg-cyan-400/20',
    textColor: 'text-cyan-400',
    speed: 3,
    quality: 2,
    cost: 1,
    features: ['Veloce', 'Flash'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['aiml-luma-ray-2', 'aiml-luma-ray-1.6'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'luma/ray-flash-2',
    category: 'Luma',
  },

  // ============ AI/ML API - SORA (OPENAI) ============
  'aiml-sora-2-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-sora-2-t2v',
    name: 'AI/ML: Sora 2 Text-to-Video',
    shortName: 'Sora 2 T2V',
    description: 'OpenAI Sora 2, alta qualità',
    color: 'bg-red-500',
    badgeColor: 'bg-red-500/20',
    textColor: 'text-red-500',
    speed: 1,
    quality: 3,
    cost: 3,
    features: ['OpenAI', 'Alta qualità', 'Fino a 20s'],
    estimatedTime: '5-10 min',
    fallbackOrder: ['aiml-sora-2-pro-t2v', 'aiml-veo3.1-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
      { value: '15', label: '15 secondi' },
      { value: '20', label: '20 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
      { value: '4k', label: '4K (Ultra HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
      { value: '1:1', label: '1:1 (Quadrato)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'sora-2-t2v',
    category: 'Sora',
  },
  'aiml-sora-2-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-sora-2-i2v',
    name: 'AI/ML: Sora 2 Image-to-Video',
    shortName: 'Sora 2 I2V',
    description: 'OpenAI Sora 2 da immagine',
    color: 'bg-red-500',
    badgeColor: 'bg-red-500/20',
    textColor: 'text-red-500',
    speed: 1,
    quality: 3,
    cost: 3,
    features: ['OpenAI', 'I2V', 'Alta qualità'],
    estimatedTime: '5-10 min',
    fallbackOrder: ['aiml-sora-2-pro-i2v', 'aiml-veo3.1-i2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
      { value: '15', label: '15 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'sora-2-i2v',
    category: 'Sora',
  },
  'aiml-sora-2-pro-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-sora-2-pro-t2v',
    name: 'AI/ML: Sora 2 Pro Text-to-Video',
    shortName: 'Sora 2 Pro T2V',
    description: 'OpenAI Sora 2 Pro, massima qualità',
    color: 'bg-red-600',
    badgeColor: 'bg-red-600/20',
    textColor: 'text-red-600',
    speed: 1,
    quality: 3,
    cost: 3,
    features: ['OpenAI Pro', 'Premium', 'Qualità massima'],
    estimatedTime: '8-15 min',
    fallbackOrder: ['aiml-sora-2-t2v', 'aiml-veo3.1-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
      { value: '15', label: '15 secondi' },
      { value: '20', label: '20 secondi' },
    ],
    resolutions: [
      { value: '1080p', label: '1080p (Full HD)' },
      { value: '4k', label: '4K (Ultra HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'sora-2-pro-t2v',
    category: 'Sora',
  },
  'aiml-sora-2-pro-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-sora-2-pro-i2v',
    name: 'AI/ML: Sora 2 Pro Image-to-Video',
    shortName: 'Sora 2 Pro I2V',
    description: 'OpenAI Sora 2 Pro da immagine',
    color: 'bg-red-600',
    badgeColor: 'bg-red-600/20',
    textColor: 'text-red-600',
    speed: 1,
    quality: 3,
    cost: 3,
    features: ['OpenAI Pro', 'I2V Premium'],
    estimatedTime: '8-15 min',
    fallbackOrder: ['aiml-sora-2-i2v', 'aiml-veo3.1-i2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
      { value: '15', label: '15 secondi' },
    ],
    resolutions: [
      { value: '1080p', label: '1080p (Full HD)' },
      { value: '4k', label: '4K (Ultra HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'sora-2-pro-i2v',
    category: 'Sora',
  },

  // ============ AI/ML API - MINIMAX ============
  'aiml-minimax-video-01': {
    ...aimlBaseConfig,
    id: 'aiml-minimax-video-01',
    name: 'AI/ML: MiniMax Video-01',
    shortName: 'Video-01',
    description: 'MiniMax veloce ed economico',
    color: 'bg-pink-500',
    badgeColor: 'bg-pink-500/20',
    textColor: 'text-pink-500',
    speed: 3,
    quality: 2,
    cost: 1,
    features: ['Veloce', 'Economico'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['aiml-minimax-hailuo-02', 'aiml-minimax-hailuo-2.3'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'video-01',
    category: 'MiniMax',
  },
  'aiml-minimax-hailuo-02': {
    ...aimlBaseConfig,
    id: 'aiml-minimax-hailuo-02',
    name: 'AI/ML: Hailuo 02',
    shortName: 'Hailuo 02',
    description: 'Hailuo migliorato',
    color: 'bg-pink-500',
    badgeColor: 'bg-pink-500/20',
    textColor: 'text-pink-500',
    speed: 3,
    quality: 2,
    cost: 1,
    features: ['Veloce', 'Hailuo 02'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['aiml-minimax-hailuo-2.3', 'aiml-minimax-video-01'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'minimax/hailuo-02',
    category: 'MiniMax',
  },
  'aiml-minimax-hailuo-2.3': {
    ...aimlBaseConfig,
    id: 'aiml-minimax-hailuo-2.3',
    name: 'AI/ML: Hailuo 2.3',
    shortName: 'Hailuo 2.3',
    description: 'Ultimo Hailuo, qualità migliorata',
    color: 'bg-pink-600',
    badgeColor: 'bg-pink-600/20',
    textColor: 'text-pink-600',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Ultimo modello', 'Qualità migliorata'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-minimax-hailuo-2.3-fast', 'aiml-minimax-hailuo-02'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'minimax/hailuo-2.3',
    category: 'MiniMax',
  },
  'aiml-minimax-hailuo-2.3-fast': {
    ...aimlBaseConfig,
    id: 'aiml-minimax-hailuo-2.3-fast',
    name: 'AI/ML: Hailuo 2.3 Fast',
    shortName: 'Hailuo 2.3 Fast',
    description: 'Hailuo 2.3 veloce',
    color: 'bg-pink-400',
    badgeColor: 'bg-pink-400/20',
    textColor: 'text-pink-400',
    speed: 3,
    quality: 2,
    cost: 1,
    features: ['Veloce', 'Hailuo Fast'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['aiml-minimax-hailuo-2.3', 'aiml-minimax-hailuo-02'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'minimax/hailuo-2.3-fast',
    category: 'MiniMax',
  },

  // ============ AI/ML API - PIXVERSE ============
  'aiml-pixverse-v5-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-pixverse-v5-t2v',
    name: 'AI/ML: PixVerse v5 Text-to-Video',
    shortName: 'PixVerse v5 T2V',
    description: 'PixVerse v5 text-to-video',
    color: 'bg-amber-500',
    badgeColor: 'bg-amber-500/20',
    textColor: 'text-amber-500',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['T2V', 'PixVerse v5'],
    estimatedTime: '2-3 min',
    fallbackOrder: ['aiml-pixverse-v5.5-t2v', 'aiml-pixverse-v5-i2v'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'pixverse/v5/text-to-video',
    category: 'PixVerse',
  },
  'aiml-pixverse-v5-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-pixverse-v5-i2v',
    name: 'AI/ML: PixVerse v5 Image-to-Video',
    shortName: 'PixVerse v5 I2V',
    description: 'PixVerse v5 image-to-video',
    color: 'bg-amber-500',
    badgeColor: 'bg-amber-500/20',
    textColor: 'text-amber-500',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['I2V', 'PixVerse v5'],
    estimatedTime: '2-3 min',
    fallbackOrder: ['aiml-pixverse-v5.5-i2v', 'aiml-pixverse-v5-t2v'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'pixverse/v5/image-to-video',
    category: 'PixVerse',
  },
  'aiml-pixverse-v5-transition': {
    ...aimlBaseConfig,
    id: 'aiml-pixverse-v5-transition',
    name: 'AI/ML: PixVerse v5 Transition',
    shortName: 'PixVerse Trans',
    description: 'Transizioni fluide tra scene',
    color: 'bg-amber-600',
    badgeColor: 'bg-amber-600/20',
    textColor: 'text-amber-600',
    speed: 2,
    quality: 2,
    cost: 2,
    features: ['Transizioni', 'Scene blend'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-pixverse-v5-i2v', 'aiml-veo3.1-first-last-i2v'],
    durations: [
      { value: '4', label: '4 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'pixverse/v5/transition',
    category: 'PixVerse',
  },
  'aiml-pixverse-v5.5-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-pixverse-v5.5-t2v',
    name: 'AI/ML: PixVerse v5.5 Text-to-Video',
    shortName: 'PixVerse 5.5 T2V',
    description: 'Ultimo PixVerse, miglior qualità',
    color: 'bg-amber-600',
    badgeColor: 'bg-amber-600/20',
    textColor: 'text-amber-600',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['v5.5', 'Miglior qualità'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-pixverse-v5-t2v', 'aiml-pixverse-v5.5-i2v'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'pixverse/v5-5-text-to-video',
    category: 'PixVerse',
  },
  'aiml-pixverse-v5.5-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-pixverse-v5.5-i2v',
    name: 'AI/ML: PixVerse v5.5 Image-to-Video',
    shortName: 'PixVerse 5.5 I2V',
    description: 'Ultimo PixVerse I2V',
    color: 'bg-amber-600',
    badgeColor: 'bg-amber-600/20',
    textColor: 'text-amber-600',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['v5.5', 'I2V avanzato'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-pixverse-v5-i2v', 'aiml-pixverse-v5.5-t2v'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'pixverse/v5-5-image-to-video',
    category: 'PixVerse',
  },

  // ============ AI/ML API - GOOGLE VEO ============
  'aiml-veo2-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-veo2-t2v',
    name: 'AI/ML: Veo 2 Text-to-Video',
    shortName: 'Veo 2 T2V',
    description: 'Google Veo 2 via AI/ML',
    color: 'bg-blue-500',
    badgeColor: 'bg-blue-500/20',
    textColor: 'text-blue-500',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Google Veo 2', 'T2V'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-veo3', 'aiml-veo3.1-t2v'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'veo2',
    category: 'Veo',
  },
  'aiml-veo2-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-veo2-i2v',
    name: 'AI/ML: Veo 2 Image-to-Video',
    shortName: 'Veo 2 I2V',
    description: 'Google Veo 2 I2V via AI/ML',
    color: 'bg-blue-500',
    badgeColor: 'bg-blue-500/20',
    textColor: 'text-blue-500',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Google Veo 2', 'I2V'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-veo3-i2v', 'aiml-veo3.1-i2v'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'veo2/image-to-video',
    category: 'Veo',
  },
  'aiml-veo3': {
    ...aimlBaseConfig,
    id: 'aiml-veo3',
    name: 'AI/ML: Veo 3',
    shortName: 'Veo 3',
    description: 'Google Veo 3 con audio nativo',
    color: 'bg-blue-600',
    badgeColor: 'bg-blue-600/20',
    textColor: 'text-blue-600',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Veo 3', 'Audio nativo'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-veo3.1-t2v', 'aiml-veo3-fast'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'google/veo3',
    category: 'Veo',
  },
  'aiml-veo3-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-veo3-i2v',
    name: 'AI/ML: Veo 3 Image-to-Video',
    shortName: 'Veo 3 I2V',
    description: 'Google Veo 3 I2V',
    color: 'bg-blue-600',
    badgeColor: 'bg-blue-600/20',
    textColor: 'text-blue-600',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Veo 3', 'I2V'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-veo3.1-i2v', 'aiml-veo3-i2v-fast'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'google/veo-3.0-i2v',
    category: 'Veo',
  },
  'aiml-veo3-fast': {
    ...aimlBaseConfig,
    id: 'aiml-veo3-fast',
    name: 'AI/ML: Veo 3 Fast',
    shortName: 'Veo 3 Fast',
    description: 'Veo 3 veloce',
    color: 'bg-blue-400',
    badgeColor: 'bg-blue-400/20',
    textColor: 'text-blue-400',
    speed: 3,
    quality: 2,
    cost: 1,
    features: ['Veloce', 'Veo 3 Fast'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['aiml-veo3', 'aiml-veo3.1-t2v-fast'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'google/veo-3.0-fast',
    category: 'Veo',
  },
  'aiml-veo3-i2v-fast': {
    ...aimlBaseConfig,
    id: 'aiml-veo3-i2v-fast',
    name: 'AI/ML: Veo 3 I2V Fast',
    shortName: 'Veo 3 I2V Fast',
    description: 'Veo 3 I2V veloce',
    color: 'bg-blue-400',
    badgeColor: 'bg-blue-400/20',
    textColor: 'text-blue-400',
    speed: 3,
    quality: 2,
    cost: 1,
    features: ['Veloce', 'I2V Fast'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['aiml-veo3-i2v', 'aiml-veo3.1-i2v-fast'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'google/veo-3.0-i2v-fast',
    category: 'Veo',
  },
  'aiml-veo3.1-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-veo3.1-t2v',
    name: 'AI/ML: Veo 3.1 Text-to-Video',
    shortName: 'Veo 3.1 T2V',
    description: 'Ultimo Veo 3.1, massima qualità',
    color: 'bg-blue-700',
    badgeColor: 'bg-blue-700/20',
    textColor: 'text-blue-700',
    speed: 2,
    quality: 3,
    cost: 3,
    features: ['Ultimo modello', 'Audio nativo', 'Premium'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-veo3', 'aiml-veo3.1-t2v-fast'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'google/veo-3.1-t2v',
    category: 'Veo',
  },
  'aiml-veo3.1-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-veo3.1-i2v',
    name: 'AI/ML: Veo 3.1 Image-to-Video',
    shortName: 'Veo 3.1 I2V',
    description: 'Ultimo Veo 3.1 I2V',
    color: 'bg-blue-700',
    badgeColor: 'bg-blue-700/20',
    textColor: 'text-blue-700',
    speed: 2,
    quality: 3,
    cost: 3,
    features: ['Ultimo modello', 'I2V Premium'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-veo3-i2v', 'aiml-veo3.1-i2v-fast'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'google/veo-3.1-i2v',
    category: 'Veo',
  },
  'aiml-veo3.1-t2v-fast': {
    ...aimlBaseConfig,
    id: 'aiml-veo3.1-t2v-fast',
    name: 'AI/ML: Veo 3.1 T2V Fast',
    shortName: 'Veo 3.1 Fast',
    description: 'Veo 3.1 veloce',
    color: 'bg-blue-500',
    badgeColor: 'bg-blue-500/20',
    textColor: 'text-blue-500',
    speed: 3,
    quality: 2,
    cost: 2,
    features: ['Veloce', 'Veo 3.1 Fast'],
    estimatedTime: '1-3 min',
    fallbackOrder: ['aiml-veo3.1-t2v', 'aiml-veo3-fast'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'google/veo-3.1-t2v-fast',
    category: 'Veo',
  },
  'aiml-veo3.1-i2v-fast': {
    ...aimlBaseConfig,
    id: 'aiml-veo3.1-i2v-fast',
    name: 'AI/ML: Veo 3.1 I2V Fast',
    shortName: 'Veo 3.1 I2V Fast',
    description: 'Veo 3.1 I2V veloce',
    color: 'bg-blue-500',
    badgeColor: 'bg-blue-500/20',
    textColor: 'text-blue-500',
    speed: 3,
    quality: 2,
    cost: 2,
    features: ['Veloce', 'I2V Fast'],
    estimatedTime: '1-3 min',
    fallbackOrder: ['aiml-veo3.1-i2v', 'aiml-veo3-i2v-fast'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'google/veo-3.1-i2v-fast',
    category: 'Veo',
  },
  'aiml-veo3.1-ref-to-video': {
    ...aimlBaseConfig,
    id: 'aiml-veo3.1-ref-to-video',
    name: 'AI/ML: Veo 3.1 Reference-to-Video',
    shortName: 'Veo 3.1 R2V',
    description: 'Video da immagine reference',
    color: 'bg-blue-600',
    badgeColor: 'bg-blue-600/20',
    textColor: 'text-blue-600',
    speed: 2,
    quality: 3,
    cost: 3,
    features: ['Reference-to-video', 'Stile coerente'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-veo3.1-i2v', 'aiml-kling-o1'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'google/veo-3.1-reference-to-video',
    category: 'Veo',
  },
  'aiml-veo3.1-first-last-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-veo3.1-first-last-i2v',
    name: 'AI/ML: Veo 3.1 First-Last Frame',
    shortName: 'Veo 3.1 FL',
    description: 'Video da frame iniziale e finale',
    color: 'bg-blue-600',
    badgeColor: 'bg-blue-600/20',
    textColor: 'text-blue-600',
    speed: 2,
    quality: 3,
    cost: 3,
    features: ['First-Last frame', 'Transizione fluida'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-pixverse-v5-transition', 'aiml-kling-v1.6-multi-i2v'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'google/veo-3.1-first-last-image-to-video',
    category: 'Veo',
  },

  // ============ AI/ML API - ALIBABA WAN ============
  'aiml-wan-2.1-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-wan-2.1-t2v',
    name: 'AI/ML: Wan 2.1 Text-to-Video',
    shortName: 'Wan 2.1 T2V',
    description: 'Alibaba Wan 2.1 T2V economico',
    color: 'bg-violet-500',
    badgeColor: 'bg-violet-500/20',
    textColor: 'text-violet-500',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['Economico', 'Alibaba Wan'],
    estimatedTime: '2-3 min',
    fallbackOrder: ['aiml-wan-2.5-t2v', 'aiml-wan-2.6-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '480p', label: '480p (Standard)' },
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'alibaba/wan-2-1-t2v',
    category: 'Wan',
  },
  'aiml-wan-2.1-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-wan-2.1-i2v',
    name: 'AI/ML: Wan 2.1 Image-to-Video',
    shortName: 'Wan 2.1 I2V',
    description: 'Alibaba Wan 2.1 I2V economico',
    color: 'bg-violet-500',
    badgeColor: 'bg-violet-500/20',
    textColor: 'text-violet-500',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['Economico', 'I2V'],
    estimatedTime: '2-3 min',
    fallbackOrder: ['aiml-wan-2.6-i2v', 'aiml-wan-2.5-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '480p', label: '480p (Standard)' },
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'alibaba/wan-2-1-i2v',
    category: 'Wan',
  },
  'aiml-wan-2.5-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-wan-2.5-t2v',
    name: 'AI/ML: Wan 2.5 Text-to-Video',
    shortName: 'Wan 2.5 T2V',
    description: 'Alibaba Wan 2.5 migliorato',
    color: 'bg-violet-600',
    badgeColor: 'bg-violet-600/20',
    textColor: 'text-violet-600',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['Bilanciato', 'Wan 2.5'],
    estimatedTime: '2-3 min',
    fallbackOrder: ['aiml-wan-2.6-t2v', 'aiml-wan-2.1-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'alibaba/wan-2-5-t2v',
    category: 'Wan',
  },
  'aiml-wan-2.6-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-wan-2.6-t2v',
    name: 'AI/ML: Wan 2.6 Text-to-Video',
    shortName: 'Wan 2.6 T2V',
    description: 'Ultimo Wan 2.6',
    color: 'bg-violet-700',
    badgeColor: 'bg-violet-700/20',
    textColor: 'text-violet-700',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Ultimo modello', 'Wan 2.6'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-wan-2.5-t2v', 'aiml-wan-2.6-i2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'alibaba/wan-2-6-t2v',
    category: 'Wan',
  },
  'aiml-wan-2.6-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-wan-2.6-i2v',
    name: 'AI/ML: Wan 2.6 Image-to-Video',
    shortName: 'Wan 2.6 I2V',
    description: 'Ultimo Wan 2.6 I2V',
    color: 'bg-violet-700',
    badgeColor: 'bg-violet-700/20',
    textColor: 'text-violet-700',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Ultimo modello', 'I2V'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-wan-2.6-t2v', 'aiml-wan-2.1-i2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'alibaba/wan-2-6-i2v',
    category: 'Wan',
  },
  'aiml-wan-2.6-r2v': {
    ...aimlBaseConfig,
    id: 'aiml-wan-2.6-r2v',
    name: 'AI/ML: Wan 2.6 Reference-to-Video',
    shortName: 'Wan 2.6 R2V',
    description: 'Video da reference image',
    color: 'bg-violet-600',
    badgeColor: 'bg-violet-600/20',
    textColor: 'text-violet-600',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Reference-to-video', 'Stile coerente'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-wan-2.6-i2v', 'aiml-veo3.1-ref-to-video'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'alibaba/wan-2-6-r2v',
    category: 'Wan',
  },

  // ============ AI/ML API - BYTEDANCE SEEDANCE ============
  'aiml-seedance-lite-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-seedance-lite-t2v',
    name: 'AI/ML: Seedance Lite T2V',
    shortName: 'Seedance Lite',
    description: 'ByteDance Seedance economico',
    color: 'bg-emerald-500',
    badgeColor: 'bg-emerald-500/20',
    textColor: 'text-emerald-500',
    speed: 3,
    quality: 2,
    cost: 1,
    features: ['Veloce', 'Economico', 'ByteDance'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['aiml-seedance-pro-t2v', 'aiml-seedance-lite-i2v'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'bytedance/seedance-1-0-lite-t2v',
    category: 'Seedance',
  },
  'aiml-seedance-lite-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-seedance-lite-i2v',
    name: 'AI/ML: Seedance Lite I2V',
    shortName: 'Seedance Lite I2V',
    description: 'ByteDance Seedance Lite I2V',
    color: 'bg-emerald-500',
    badgeColor: 'bg-emerald-500/20',
    textColor: 'text-emerald-500',
    speed: 3,
    quality: 2,
    cost: 1,
    features: ['Veloce', 'I2V'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['aiml-seedance-pro-i2v', 'aiml-seedance-lite-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'bytedance/seedance-1-0-lite-i2v',
    category: 'Seedance',
  },
  'aiml-seedance-pro-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-seedance-pro-t2v',
    name: 'AI/ML: Seedance Pro T2V',
    shortName: 'Seedance Pro',
    description: 'ByteDance Seedance Pro',
    color: 'bg-emerald-600',
    badgeColor: 'bg-emerald-600/20',
    textColor: 'text-emerald-600',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Pro quality', 'ByteDance'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-seedance-lite-t2v', 'aiml-seedance-pro-i2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'bytedance/seedance-1-0-pro-t2v',
    category: 'Seedance',
  },
  'aiml-seedance-pro-i2v': {
    ...aimlBaseConfig,
    id: 'aiml-seedance-pro-i2v',
    name: 'AI/ML: Seedance Pro I2V',
    shortName: 'Seedance Pro I2V',
    description: 'ByteDance Seedance Pro I2V',
    color: 'bg-emerald-600',
    badgeColor: 'bg-emerald-600/20',
    textColor: 'text-emerald-600',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Pro quality', 'I2V'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-seedance-lite-i2v', 'aiml-seedance-pro-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'bytedance/seedance-1-0-pro-i2v',
    category: 'Seedance',
  },
  'aiml-omnihuman': {
    ...aimlBaseConfig,
    id: 'aiml-omnihuman',
    name: 'AI/ML: OmniHuman',
    shortName: 'OmniHuman',
    description: 'Animazione avatar realistici',
    color: 'bg-emerald-700',
    badgeColor: 'bg-emerald-700/20',
    textColor: 'text-emerald-700',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Avatar', 'Animazione umana'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-omnihuman-1.5', 'aiml-runway-act-two'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'bytedance/omnihuman',
    category: 'Seedance',
  },
  'aiml-omnihuman-1.5': {
    ...aimlBaseConfig,
    id: 'aiml-omnihuman-1.5',
    name: 'AI/ML: OmniHuman v1.5',
    shortName: 'OmniHuman 1.5',
    description: 'OmniHuman v1.5 migliorato',
    color: 'bg-emerald-800',
    badgeColor: 'bg-emerald-800/20',
    textColor: 'text-emerald-800',
    speed: 2,
    quality: 3,
    cost: 3,
    features: ['Avatar avanzato', 'v1.5'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-omnihuman', 'aiml-runway-act-two'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'bytedance/omnihuman/v1.5',
    category: 'Seedance',
  },

  // ============ AI/ML API - KREA ============
  'aiml-krea-wan-14b-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-krea-wan-14b-t2v',
    name: 'AI/ML: Krea WAN 14B T2V',
    shortName: 'Krea WAN T2V',
    description: 'Krea WAN 14B text-to-video',
    color: 'bg-rose-500',
    badgeColor: 'bg-rose-500/20',
    textColor: 'text-rose-500',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['Krea', 'WAN 14B'],
    estimatedTime: '2-3 min',
    fallbackOrder: ['aiml-krea-wan-14b-v2v', 'aiml-wan-2.6-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'krea/krea-wan-14b/text-to-video',
    category: 'Krea',
  },
  'aiml-krea-wan-14b-v2v': {
    ...aimlBaseConfig,
    id: 'aiml-krea-wan-14b-v2v',
    name: 'AI/ML: Krea WAN 14B V2V',
    shortName: 'Krea WAN V2V',
    description: 'Krea WAN 14B video-to-video',
    color: 'bg-rose-500',
    badgeColor: 'bg-rose-500/20',
    textColor: 'text-rose-500',
    speed: 2,
    quality: 2,
    cost: 2,
    features: ['V2V', 'Editing video'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['aiml-krea-wan-14b-t2v', 'aiml-kling-o1'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    modelId: 'krea/krea-wan-14b/video-to-video',
    category: 'Krea',
  },

  // ============ AI/ML API - KANDINSKY ============
  'aiml-kandinsky5-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-kandinsky5-t2v',
    name: 'AI/ML: Kandinsky 5 T2V',
    shortName: 'Kandinsky 5',
    description: 'Sber AI Kandinsky 5',
    color: 'bg-teal-500',
    badgeColor: 'bg-teal-500/20',
    textColor: 'text-teal-500',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['Kandinsky 5', 'Sber AI'],
    estimatedTime: '2-3 min',
    fallbackOrder: ['aiml-kandinsky5-distill-t2v', 'aiml-wan-2.5-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'sber-ai/kandinsky5-t2v',
    category: 'Kandinsky',
  },
  'aiml-kandinsky5-distill-t2v': {
    ...aimlBaseConfig,
    id: 'aiml-kandinsky5-distill-t2v',
    name: 'AI/ML: Kandinsky 5 Distill',
    shortName: 'Kandinsky Distill',
    description: 'Kandinsky 5 Distill veloce',
    color: 'bg-teal-400',
    badgeColor: 'bg-teal-400/20',
    textColor: 'text-teal-400',
    speed: 3,
    quality: 2,
    cost: 1,
    features: ['Veloce', 'Distillato'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['aiml-kandinsky5-t2v', 'aiml-seedance-lite-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    modelId: 'sber-ai/kandinsky5-distill-t2v',
    category: 'Kandinsky',
  },

  // ============ AI/ML API - VEED FABRIC ============
  'aiml-veed-fabric-1.0': {
    ...aimlBaseConfig,
    id: 'aiml-veed-fabric-1.0',
    name: 'AI/ML: VEED Fabric 1.0',
    shortName: 'Fabric 1.0',
    description: 'VEED Fabric per editing video',
    color: 'bg-indigo-500',
    badgeColor: 'bg-indigo-500/20',
    textColor: 'text-indigo-500',
    speed: 2,
    quality: 2,
    cost: 2,
    features: ['VEED', 'Editing video'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['aiml-veed-fabric-1.0-fast', 'aiml-krea-wan-14b-v2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'veed/fabric-1.0',
    category: 'VEED',
  },
  'aiml-veed-fabric-1.0-fast': {
    ...aimlBaseConfig,
    id: 'aiml-veed-fabric-1.0-fast',
    name: 'AI/ML: VEED Fabric 1.0 Fast',
    shortName: 'Fabric Fast',
    description: 'VEED Fabric veloce',
    color: 'bg-indigo-400',
    badgeColor: 'bg-indigo-400/20',
    textColor: 'text-indigo-400',
    speed: 3,
    quality: 2,
    cost: 1,
    features: ['Veloce', 'VEED Fast'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['aiml-veed-fabric-1.0', 'aiml-seedance-lite-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    modelId: 'veed/fabric-1.0-fast',
    category: 'VEED',
  },

  // ============ PIAPI PROVIDERS ============
  'piapi-kling-2.1': {
    id: 'piapi-kling-2.1',
    name: 'PiAPI: Kling 2.1',
    shortName: 'Kling 2.1',
    group: 'piapi',
    description: 'Economico, buona qualità base',
    color: 'bg-orange-400',
    badgeColor: 'bg-orange-400/20',
    textColor: 'text-orange-400',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['Economico'],
    estimatedTime: '2-3 min',
    fallbackOrder: ['piapi-kling-2.5', 'piapi-hailuo'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    requiresApiKey: 'PIAPI_API_KEY',
    category: 'PiAPI',
  },
  'piapi-kling-2.5': {
    id: 'piapi-kling-2.5',
    name: 'PiAPI: Kling 2.5',
    shortName: 'Kling 2.5',
    group: 'piapi',
    description: 'Ottimo rapporto qualità/prezzo',
    color: 'bg-orange-500',
    badgeColor: 'bg-orange-500/20',
    textColor: 'text-orange-500',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Ottimo Q/P', 'Transizioni fluide'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['piapi-kling-2.6', 'piapi-hailuo'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    requiresApiKey: 'PIAPI_API_KEY',
    category: 'PiAPI',
  },
  'piapi-kling-2.6': {
    id: 'piapi-kling-2.6',
    name: 'PiAPI: Kling 2.6',
    shortName: 'Kling 2.6',
    group: 'piapi',
    description: 'Ultimo modello con motion control',
    color: 'bg-orange-600',
    badgeColor: 'bg-orange-600/20',
    textColor: 'text-orange-600',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Motion control', 'Nuovo modello'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['piapi-kling-2.5', 'piapi-hailuo'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    requiresApiKey: 'PIAPI_API_KEY',
    category: 'PiAPI',
  },
  'piapi-hailuo': {
    id: 'piapi-hailuo',
    name: 'PiAPI: Hailuo',
    shortName: 'Hailuo',
    group: 'piapi',
    description: 'Veloce ed economico',
    color: 'bg-pink-500',
    badgeColor: 'bg-pink-500/20',
    textColor: 'text-pink-500',
    speed: 3,
    quality: 2,
    cost: 1,
    features: ['Veloce', 'Economico'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['piapi-wan', 'piapi-kling-2.5'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    requiresApiKey: 'PIAPI_API_KEY',
    category: 'PiAPI',
  },
  'piapi-luma': {
    id: 'piapi-luma',
    name: 'PiAPI: Luma',
    shortName: 'Luma',
    group: 'piapi',
    description: 'Stile cinematico unico',
    color: 'bg-cyan-500',
    badgeColor: 'bg-cyan-500/20',
    textColor: 'text-cyan-500',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Cinematico', 'Stile unico'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['piapi-kling-2.5', 'piapi-hailuo'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    requiresApiKey: 'PIAPI_API_KEY',
    category: 'PiAPI',
  },
  'piapi-wan': {
    id: 'piapi-wan',
    name: 'PiAPI: Wan',
    shortName: 'Wan',
    group: 'piapi',
    description: 'Ottimo per scene naturali',
    color: 'bg-violet-500',
    badgeColor: 'bg-violet-500/20',
    textColor: 'text-violet-500',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['Scene naturali', 'Economico'],
    estimatedTime: '2-3 min',
    fallbackOrder: ['piapi-hailuo', 'piapi-kling-2.5'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '480p', label: '480p (Standard)' },
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    requiresApiKey: 'PIAPI_API_KEY',
    category: 'PiAPI',
  },
  'piapi-hunyuan': {
    id: 'piapi-hunyuan',
    name: 'PiAPI: Hunyuan',
    shortName: 'Hunyuan',
    group: 'piapi',
    description: 'Volti realistici e dettagliati',
    color: 'bg-amber-500',
    badgeColor: 'bg-amber-500/20',
    textColor: 'text-amber-500',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Volti realistici', 'Dettagli'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['piapi-kling-2.5', 'piapi-hailuo'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    requiresApiKey: 'PIAPI_API_KEY',
    category: 'PiAPI',
  },
  'piapi-skyreels': {
    id: 'piapi-skyreels',
    name: 'PiAPI: SkyReels V2',
    shortName: 'SkyReels',
    group: 'piapi',
    description: 'Video human-centric, ritratti e personaggi',
    color: 'bg-sky-500',
    badgeColor: 'bg-sky-500/20',
    textColor: 'text-sky-500',
    speed: 2,
    quality: 3,
    cost: 1,
    features: ['Human-centric', 'Ritratti', 'Volti realistici'],
    estimatedTime: '2-3 min',
    fallbackOrder: ['piapi-hunyuan', 'piapi-kling-2.5'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
      { value: '1:1', label: '1:1 (Quadrato)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false, // SkyReels V2 is image-to-video only
    requiresApiKey: 'PIAPI_API_KEY',
    modelId: 'Qubico/skyreels',
    category: 'PiAPI',
  },
  'piapi-framepack': {
    id: 'piapi-framepack',
    name: 'PiAPI: Framepack',
    shortName: 'Framepack',
    group: 'piapi',
    description: 'Interpolazione frame fluida tra keyframe',
    color: 'bg-teal-500',
    badgeColor: 'bg-teal-500/20',
    textColor: 'text-teal-500',
    speed: 3,
    quality: 3,
    cost: 1,
    features: ['Interpolazione', 'Start/End Frame', '30 FPS'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['piapi-skyreels', 'piapi-kling-2.5'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
      { value: '1:1', label: '1:1 (Quadrato)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false, // Framepack is image-to-video only
    supportsEndFrame: true, // Key feature: supports start + end frame interpolation
    requiresApiKey: 'PIAPI_API_KEY',
    modelId: 'Qubico/framepack',
    category: 'PiAPI',
  },
  'piapi-veo3': {
    id: 'piapi-veo3',
    name: 'PiAPI: Veo 3',
    shortName: 'Veo 3 PiAPI',
    group: 'piapi',
    description: 'Audio sync via PiAPI',
    color: 'bg-emerald-500',
    badgeColor: 'bg-emerald-500/20',
    textColor: 'text-emerald-500',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['Audio sync', 'Via PiAPI'],
    estimatedTime: '3-5 min',
    fallbackOrder: ['piapi-kling-2.5', 'piapi-hailuo'],
    durations: [
      { value: '4', label: '4 secondi' },
      { value: '6', label: '6 secondi' },
      { value: '8', label: '8 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    requiresApiKey: 'PIAPI_API_KEY',
    category: 'PiAPI',
  },
  'piapi-sora2': {
    id: 'piapi-sora2',
    name: 'PiAPI: Sora 2',
    shortName: 'Sora 2 PiAPI',
    group: 'piapi',
    description: 'OpenAI Sora, fino a 20 secondi',
    color: 'bg-red-500',
    badgeColor: 'bg-red-500/20',
    textColor: 'text-red-500',
    speed: 1,
    quality: 3,
    cost: 3,
    features: ['OpenAI', 'Fino a 20s', 'Alta qualità'],
    estimatedTime: '5-10 min',
    fallbackOrder: ['piapi-kling-2.5', 'piapi-veo3'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '10', label: '10 secondi' },
      { value: '15', label: '15 secondi' },
      { value: '20', label: '20 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
      { value: '4k', label: '4K (Ultra HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    requiresApiKey: 'PIAPI_API_KEY',
    category: 'PiAPI',
  },

  // ============ FREEPIK ============
  freepik: {
    id: 'freepik',
    name: 'Freepik MiniMax',
    shortName: 'Freepik',
    group: 'freepik',
    description: 'Veloce con transizioni fluide',
    color: 'bg-fuchsia-500',
    badgeColor: 'bg-fuchsia-500/20',
    textColor: 'text-fuchsia-500',
    speed: 3,
    quality: 2,
    cost: 1,
    features: ['Veloce', 'Transizioni'],
    estimatedTime: '1-2 min',
    fallbackOrder: ['piapi-hailuo', 'piapi-kling-2.5'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '720p', label: '720p (HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: true,
    requiresApiKey: 'FREEPIK_API_KEY',
    category: 'Freepik',
  },

  // ============ VIDU ============
  'vidu-q3-turbo-t2v': {
    id: 'vidu-q3-turbo-t2v',
    name: 'Vidu Q3 Turbo (T2V)',
    shortName: 'Vidu Q3 Turbo',
    group: 'vidu',
    description: 'Generazione veloce con audio sincronizzato',
    color: 'bg-teal-500',
    badgeColor: 'bg-teal-500/20',
    textColor: 'text-teal-500',
    speed: 3,
    quality: 3,
    cost: 2,
    features: ['Turbo', 'Audio sync', 'Fino a 16s'],
    estimatedTime: '1-3 min',
    fallbackOrder: ['vidu-q3-pro-t2v', 'vidu-q2-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '8', label: '8 secondi' },
      { value: '10', label: '10 secondi' },
      { value: '16', label: '16 secondi' },
    ],
    resolutions: [
      { value: '540p', label: '540p' },
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
      { value: '1:1', label: '1:1 (Quadrato)' },
      { value: '4:3', label: '4:3 (Standard)' },
      { value: '3:4', label: '3:4 (Ritratto)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    requiresApiKey: 'VIDU_API_KEY',
    modelId: 'viduq3-turbo',
    category: 'Vidu',
  },
  'vidu-q3-turbo-i2v': {
    id: 'vidu-q3-turbo-i2v',
    name: 'Vidu Q3 Turbo (I2V)',
    shortName: 'Vidu Q3T I2V',
    group: 'vidu',
    description: 'Image-to-Video veloce con audio',
    color: 'bg-teal-500',
    badgeColor: 'bg-teal-500/20',
    textColor: 'text-teal-500',
    speed: 3,
    quality: 3,
    cost: 2,
    features: ['Turbo', 'Audio sync', 'I2V'],
    estimatedTime: '1-3 min',
    fallbackOrder: ['vidu-q3-pro-i2v', 'vidu-q2-i2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '8', label: '8 secondi' },
      { value: '10', label: '10 secondi' },
      { value: '16', label: '16 secondi' },
    ],
    resolutions: [
      { value: '540p', label: '540p' },
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    requiresApiKey: 'VIDU_API_KEY',
    modelId: 'viduq3-turbo',
    category: 'Vidu',
  },
  'vidu-q3-pro-t2v': {
    id: 'vidu-q3-pro-t2v',
    name: 'Vidu Q3 Pro (T2V)',
    shortName: 'Vidu Q3 Pro',
    group: 'vidu',
    description: 'Massima qualità con audio-video sync, shot segmentation',
    color: 'bg-teal-600',
    badgeColor: 'bg-teal-600/20',
    textColor: 'text-teal-600',
    speed: 2,
    quality: 3,
    cost: 3,
    features: ['Pro quality', 'Audio sync', 'Shot segmentation', 'Fino a 16s'],
    estimatedTime: '2-5 min',
    fallbackOrder: ['vidu-q3-turbo-t2v', 'vidu-q2-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '8', label: '8 secondi' },
      { value: '10', label: '10 secondi' },
      { value: '16', label: '16 secondi' },
    ],
    resolutions: [
      { value: '540p', label: '540p' },
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
      { value: '1:1', label: '1:1 (Quadrato)' },
      { value: '4:3', label: '4:3 (Standard)' },
      { value: '3:4', label: '3:4 (Ritratto)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    requiresApiKey: 'VIDU_API_KEY',
    modelId: 'viduq3-pro',
    category: 'Vidu',
  },
  'vidu-q3-pro-i2v': {
    id: 'vidu-q3-pro-i2v',
    name: 'Vidu Q3 Pro (I2V)',
    shortName: 'Vidu Q3P I2V',
    group: 'vidu',
    description: 'Image-to-Video Pro con audio',
    color: 'bg-teal-600',
    badgeColor: 'bg-teal-600/20',
    textColor: 'text-teal-600',
    speed: 2,
    quality: 3,
    cost: 3,
    features: ['Pro quality', 'Audio sync', 'I2V'],
    estimatedTime: '2-5 min',
    fallbackOrder: ['vidu-q3-turbo-i2v', 'vidu-q2-i2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '8', label: '8 secondi' },
      { value: '10', label: '10 secondi' },
      { value: '16', label: '16 secondi' },
    ],
    resolutions: [
      { value: '540p', label: '540p' },
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsAudio: true,
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    requiresApiKey: 'VIDU_API_KEY',
    modelId: 'viduq3-pro',
    category: 'Vidu',
  },
  'vidu-q2-t2v': {
    id: 'vidu-q2-t2v',
    name: 'Vidu Q2 (T2V)',
    shortName: 'Vidu Q2',
    group: 'vidu',
    description: 'Modello di nuova generazione, fino a 10s',
    color: 'bg-teal-400',
    badgeColor: 'bg-teal-400/20',
    textColor: 'text-teal-400',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['New gen', 'Fino a 10s', '1080p'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['vidu-q3-turbo-t2v', 'vidu-q1-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '8', label: '8 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '540p', label: '540p' },
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
      { value: '1:1', label: '1:1 (Quadrato)' },
      { value: '4:3', label: '4:3 (Standard)' },
      { value: '3:4', label: '3:4 (Ritratto)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    requiresApiKey: 'VIDU_API_KEY',
    modelId: 'viduq2',
    category: 'Vidu',
  },
  'vidu-q2-i2v': {
    id: 'vidu-q2-i2v',
    name: 'Vidu Q2 (I2V)',
    shortName: 'Vidu Q2 I2V',
    group: 'vidu',
    description: 'Image-to-Video nuova generazione',
    color: 'bg-teal-400',
    badgeColor: 'bg-teal-400/20',
    textColor: 'text-teal-400',
    speed: 2,
    quality: 3,
    cost: 2,
    features: ['New gen', 'I2V', '1080p'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['vidu-q3-turbo-i2v', 'vidu-q1-i2v'],
    durations: [
      { value: '5', label: '5 secondi' },
      { value: '8', label: '8 secondi' },
      { value: '10', label: '10 secondi' },
    ],
    resolutions: [
      { value: '540p', label: '540p' },
      { value: '720p', label: '720p (HD)' },
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    requiresApiKey: 'VIDU_API_KEY',
    modelId: 'viduq2',
    category: 'Vidu',
  },
  'vidu-q1-t2v': {
    id: 'vidu-q1-t2v',
    name: 'Vidu Q1 (T2V)',
    shortName: 'Vidu Q1',
    group: 'vidu',
    description: 'Immagini chiare, transizioni fluide, camera stabile',
    color: 'bg-teal-300',
    badgeColor: 'bg-teal-300/20',
    textColor: 'text-teal-300',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['Stabile', 'Anime', '1080p'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['vidu-q2-t2v', 'vidu-q3-turbo-t2v'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    aspectRatios: [
      { value: '16:9', label: '16:9 (Orizzontale)' },
      { value: '9:16', label: '9:16 (Verticale)' },
      { value: '1:1', label: '1:1 (Quadrato)' },
    ],
    supportsImageToVideo: false,
    supportsTextToVideo: true,
    requiresApiKey: 'VIDU_API_KEY',
    modelId: 'viduq1',
    category: 'Vidu',
  },
  'vidu-q1-i2v': {
    id: 'vidu-q1-i2v',
    name: 'Vidu Q1 (I2V)',
    shortName: 'Vidu Q1 I2V',
    group: 'vidu',
    description: 'Image-to-Video base, economico',
    color: 'bg-teal-300',
    badgeColor: 'bg-teal-300/20',
    textColor: 'text-teal-300',
    speed: 2,
    quality: 2,
    cost: 1,
    features: ['Economico', 'I2V', 'Anime'],
    estimatedTime: '2-4 min',
    fallbackOrder: ['vidu-q2-i2v', 'vidu-q3-turbo-i2v'],
    durations: [
      { value: '5', label: '5 secondi' },
    ],
    resolutions: [
      { value: '1080p', label: '1080p (Full HD)' },
    ],
    supportsImageToVideo: true,
    supportsTextToVideo: false,
    requiresApiKey: 'VIDU_API_KEY',
    modelId: 'viduq1',
    category: 'Vidu',
  },
};

// Helper per ottenere provider per gruppo
export function getProvidersByGroup(group: ProviderGroup): VideoProviderInfo[] {
  return Object.values(VIDEO_PROVIDERS).filter(p => p.group === group);
}

// Helper per ottenere provider che supportano un tipo specifico
export function getProvidersForType(type: 'text_to_video' | 'image_to_video'): VideoProviderInfo[] {
  return Object.values(VIDEO_PROVIDERS).filter(p => 
    type === 'text_to_video' ? p.supportsTextToVideo : p.supportsImageToVideo
  );
}

// Helper per ottenere l'etichetta del gruppo
export function getGroupLabel(group: ProviderGroup): string {
  const labels: Record<ProviderGroup, string> = {
    auto: 'Automatico',
    google: 'Google',
    aiml: 'AI/ML API',
    piapi: 'PiAPI',
    freepik: 'Freepik',
    vidu: 'Vidu',
  };
  return labels[group];
}

// Helper per ottenere il colore del gruppo per badge
export function getGroupBadgeStyles(group: ProviderGroup): { bg: string; text: string } {
  const styles: Record<ProviderGroup, { bg: string; text: string }> = {
    auto: { bg: 'bg-accent/20', text: 'text-accent' },
    google: { bg: 'bg-blue-500/20', text: 'text-blue-500' },
    aiml: { bg: 'bg-purple-500/20', text: 'text-purple-500' },
    piapi: { bg: 'bg-orange-500/20', text: 'text-orange-500' },
    freepik: { bg: 'bg-fuchsia-500/20', text: 'text-fuchsia-500' },
    vidu: { bg: 'bg-teal-500/20', text: 'text-teal-500' },
  };
  return styles[group];
}

// Helper per identificare il gruppo da un provider ID
export function getProviderGroup(providerId: string): ProviderGroup {
  const provider = VIDEO_PROVIDERS[providerId as VideoProviderType];
  if (provider) return provider.group;
  
  // Fallback per provider ID non standard
  if (providerId.startsWith('aiml-')) return 'aiml';
  if (providerId.startsWith('piapi-')) return 'piapi';
  if (providerId === 'google-veo' || providerId === 'veo') return 'google';
  if (providerId === 'freepik') return 'freepik';
  if (providerId.startsWith('vidu-')) return 'vidu';
  return 'auto';
}

// Helper per ottenere info provider da ID (anche con alias)
export function getProviderInfo(providerId: string): VideoProviderInfo | null {
  // Diretto match
  if (VIDEO_PROVIDERS[providerId as VideoProviderType]) {
    return VIDEO_PROVIDERS[providerId as VideoProviderType];
  }
  
  // Alias comuni
  const aliases: Record<string, VideoProviderType> = {
    'veo': 'google-veo',
    'kling': 'aiml-kling-v2.6-pro',
    'runway': 'aiml-runway-gen4-turbo',
    'sora': 'aiml-sora-2-t2v',
    'hailuo': 'aiml-minimax-hailuo-2.3',
    'luma': 'aiml-luma-ray-2',
  };
  
  if (aliases[providerId]) {
    return VIDEO_PROVIDERS[aliases[providerId]];
  }
  
  return null;
}

// Helper per ottenere provider per categoria
export function getProvidersByCategory(category: string): VideoProviderInfo[] {
  return Object.values(VIDEO_PROVIDERS).filter(p => p.category === category);
}

// Helper per ottenere tutte le categorie AI/ML
export function getAimlCategories(): string[] {
  const categories = new Set<string>();
  Object.values(VIDEO_PROVIDERS)
    .filter(p => p.group === 'aiml' && p.category)
    .forEach(p => categories.add(p.category!));
  return Array.from(categories).sort();
}

// Costi stimati per provider (in USD)
export const PROVIDER_COSTS: Record<VideoProviderType, { perSecond: number; perGeneration: number }> = {
  auto: { perSecond: 0.05, perGeneration: 0.25 },
  'google-veo': { perSecond: 0.08, perGeneration: 0.40 },
  // Runway
  'aiml-runway-gen3-turbo': { perSecond: 0.08, perGeneration: 0.40 },
  'aiml-runway-gen4-turbo': { perSecond: 0.12, perGeneration: 0.60 },
  'aiml-runway-gen4-aleph': { perSecond: 0.15, perGeneration: 0.75 },
  'aiml-runway-act-two': { perSecond: 0.10, perGeneration: 0.50 },
  // Kling
  'aiml-kling-v1-std': { perSecond: 0.03, perGeneration: 0.15 },
  'aiml-kling-v1-pro': { perSecond: 0.05, perGeneration: 0.25 },
  'aiml-kling-v1.6-std': { perSecond: 0.03, perGeneration: 0.15 },
  'aiml-kling-v1.6-pro': { perSecond: 0.05, perGeneration: 0.25 },
  'aiml-kling-v1.6-pro-effects': { perSecond: 0.06, perGeneration: 0.30 },
  'aiml-kling-v1.6-multi-i2v': { perSecond: 0.06, perGeneration: 0.30 },
  'aiml-kling-v2-master': { perSecond: 0.06, perGeneration: 0.30 },
  'aiml-kling-v2.1-std': { perSecond: 0.04, perGeneration: 0.20 },
  'aiml-kling-v2.1-pro': { perSecond: 0.06, perGeneration: 0.30 },
  'aiml-kling-v2.1-master': { perSecond: 0.08, perGeneration: 0.40 },
  'aiml-kling-v2.5-turbo-pro': { perSecond: 0.06, perGeneration: 0.30 },
  'aiml-kling-v2.6-pro': { perSecond: 0.08, perGeneration: 0.40 },
  'aiml-kling-o1': { perSecond: 0.10, perGeneration: 0.50 },
  // Luma
  'aiml-luma-ray-1.6': { perSecond: 0.06, perGeneration: 0.30 },
  'aiml-luma-ray-2': { perSecond: 0.08, perGeneration: 0.40 },
  'aiml-luma-ray-flash-2': { perSecond: 0.04, perGeneration: 0.20 },
  // Sora
  'aiml-sora-2-t2v': { perSecond: 0.15, perGeneration: 0.75 },
  'aiml-sora-2-i2v': { perSecond: 0.15, perGeneration: 0.75 },
  'aiml-sora-2-pro-t2v': { perSecond: 0.20, perGeneration: 1.00 },
  'aiml-sora-2-pro-i2v': { perSecond: 0.20, perGeneration: 1.00 },
  // MiniMax
  'aiml-minimax-video-01': { perSecond: 0.02, perGeneration: 0.10 },
  'aiml-minimax-hailuo-02': { perSecond: 0.02, perGeneration: 0.10 },
  'aiml-minimax-hailuo-2.3': { perSecond: 0.04, perGeneration: 0.20 },
  'aiml-minimax-hailuo-2.3-fast': { perSecond: 0.02, perGeneration: 0.10 },
  // PixVerse
  'aiml-pixverse-v5-t2v': { perSecond: 0.03, perGeneration: 0.15 },
  'aiml-pixverse-v5-i2v': { perSecond: 0.03, perGeneration: 0.15 },
  'aiml-pixverse-v5-transition': { perSecond: 0.04, perGeneration: 0.20 },
  'aiml-pixverse-v5.5-t2v': { perSecond: 0.04, perGeneration: 0.20 },
  'aiml-pixverse-v5.5-i2v': { perSecond: 0.04, perGeneration: 0.20 },
  // Veo via AI/ML
  'aiml-veo2-t2v': { perSecond: 0.06, perGeneration: 0.30 },
  'aiml-veo2-i2v': { perSecond: 0.06, perGeneration: 0.30 },
  'aiml-veo3': { perSecond: 0.08, perGeneration: 0.40 },
  'aiml-veo3-i2v': { perSecond: 0.08, perGeneration: 0.40 },
  'aiml-veo3-fast': { perSecond: 0.04, perGeneration: 0.20 },
  'aiml-veo3-i2v-fast': { perSecond: 0.04, perGeneration: 0.20 },
  'aiml-veo3.1-t2v': { perSecond: 0.10, perGeneration: 0.50 },
  'aiml-veo3.1-i2v': { perSecond: 0.10, perGeneration: 0.50 },
  'aiml-veo3.1-t2v-fast': { perSecond: 0.06, perGeneration: 0.30 },
  'aiml-veo3.1-i2v-fast': { perSecond: 0.06, perGeneration: 0.30 },
  'aiml-veo3.1-ref-to-video': { perSecond: 0.10, perGeneration: 0.50 },
  'aiml-veo3.1-first-last-i2v': { perSecond: 0.10, perGeneration: 0.50 },
  // Wan
  'aiml-wan-2.1-t2v': { perSecond: 0.02, perGeneration: 0.10 },
  'aiml-wan-2.1-i2v': { perSecond: 0.02, perGeneration: 0.10 },
  'aiml-wan-2.5-t2v': { perSecond: 0.03, perGeneration: 0.15 },
  'aiml-wan-2.6-t2v': { perSecond: 0.04, perGeneration: 0.20 },
  'aiml-wan-2.6-i2v': { perSecond: 0.04, perGeneration: 0.20 },
  'aiml-wan-2.6-r2v': { perSecond: 0.04, perGeneration: 0.20 },
  // Seedance
  'aiml-seedance-lite-t2v': { perSecond: 0.02, perGeneration: 0.10 },
  'aiml-seedance-lite-i2v': { perSecond: 0.02, perGeneration: 0.10 },
  'aiml-seedance-pro-t2v': { perSecond: 0.05, perGeneration: 0.25 },
  'aiml-seedance-pro-i2v': { perSecond: 0.05, perGeneration: 0.25 },
  'aiml-omnihuman': { perSecond: 0.06, perGeneration: 0.30 },
  'aiml-omnihuman-1.5': { perSecond: 0.08, perGeneration: 0.40 },
  // Krea
  'aiml-krea-wan-14b-t2v': { perSecond: 0.03, perGeneration: 0.15 },
  'aiml-krea-wan-14b-v2v': { perSecond: 0.04, perGeneration: 0.20 },
  // Kandinsky
  'aiml-kandinsky5-t2v': { perSecond: 0.02, perGeneration: 0.10 },
  'aiml-kandinsky5-distill-t2v': { perSecond: 0.01, perGeneration: 0.05 },
  // VEED
  'aiml-veed-fabric-1.0': { perSecond: 0.04, perGeneration: 0.20 },
  'aiml-veed-fabric-1.0-fast': { perSecond: 0.02, perGeneration: 0.10 },
  // PiAPI
  'piapi-kling-2.1': { perSecond: 0.03, perGeneration: 0.15 },
  'piapi-kling-2.5': { perSecond: 0.05, perGeneration: 0.25 },
  'piapi-kling-2.6': { perSecond: 0.05, perGeneration: 0.25 },
  'piapi-hailuo': { perSecond: 0.02, perGeneration: 0.10 },
  'piapi-luma': { perSecond: 0.06, perGeneration: 0.30 },
  'piapi-wan': { perSecond: 0.02, perGeneration: 0.10 },
  'piapi-hunyuan': { perSecond: 0.05, perGeneration: 0.25 },
  'piapi-skyreels': { perSecond: 0.03, perGeneration: 0.15 },
  'piapi-framepack': { perSecond: 0.02, perGeneration: 0.10 },
  'piapi-veo3': { perSecond: 0.08, perGeneration: 0.40 },
  'piapi-sora2': { perSecond: 0.15, perGeneration: 0.75 },
  freepik: { perSecond: 0.02, perGeneration: 0.10 },
  // Vidu
  'vidu-q3-turbo-t2v': { perSecond: 0.04, perGeneration: 0.20 },
  'vidu-q3-turbo-i2v': { perSecond: 0.04, perGeneration: 0.20 },
  'vidu-q3-pro-t2v': { perSecond: 0.06, perGeneration: 0.30 },
  'vidu-q3-pro-i2v': { perSecond: 0.06, perGeneration: 0.30 },
  'vidu-q2-t2v': { perSecond: 0.04, perGeneration: 0.20 },
  'vidu-q2-i2v': { perSecond: 0.04, perGeneration: 0.20 },
  'vidu-q1-t2v': { perSecond: 0.02, perGeneration: 0.10 },
  'vidu-q1-i2v': { perSecond: 0.02, perGeneration: 0.10 },
};

// Ordine di visualizzazione per provider (raggruppati)
export const PROVIDER_DISPLAY_ORDER: VideoProviderType[] = [
  'auto',
  // Google Diretto
  'google-veo',
  // AI/ML API - Runway
  'aiml-runway-gen4-turbo',
  'aiml-runway-gen3-turbo',
  'aiml-runway-gen4-aleph',
  'aiml-runway-act-two',
  // AI/ML API - Kling
  'aiml-kling-v2.6-pro',
  'aiml-kling-v2.5-turbo-pro',
  'aiml-kling-v2.1-master',
  'aiml-kling-v2.1-pro',
  'aiml-kling-v2.1-std',
  'aiml-kling-v2-master',
  'aiml-kling-v1.6-pro',
  'aiml-kling-v1.6-std',
  'aiml-kling-v1.6-pro-effects',
  'aiml-kling-v1.6-multi-i2v',
  'aiml-kling-v1-pro',
  'aiml-kling-v1-std',
  'aiml-kling-o1',
  // AI/ML API - Luma
  'aiml-luma-ray-2',
  'aiml-luma-ray-1.6',
  'aiml-luma-ray-flash-2',
  // AI/ML API - Sora
  'aiml-sora-2-pro-t2v',
  'aiml-sora-2-pro-i2v',
  'aiml-sora-2-t2v',
  'aiml-sora-2-i2v',
  // AI/ML API - Veo
  'aiml-veo3.1-t2v',
  'aiml-veo3.1-i2v',
  'aiml-veo3.1-t2v-fast',
  'aiml-veo3.1-i2v-fast',
  'aiml-veo3.1-ref-to-video',
  'aiml-veo3.1-first-last-i2v',
  'aiml-veo3',
  'aiml-veo3-i2v',
  'aiml-veo3-fast',
  'aiml-veo3-i2v-fast',
  'aiml-veo2-t2v',
  'aiml-veo2-i2v',
  // AI/ML API - MiniMax
  'aiml-minimax-hailuo-2.3',
  'aiml-minimax-hailuo-2.3-fast',
  'aiml-minimax-hailuo-02',
  'aiml-minimax-video-01',
  // AI/ML API - PixVerse
  'aiml-pixverse-v5.5-t2v',
  'aiml-pixverse-v5.5-i2v',
  'aiml-pixverse-v5-t2v',
  'aiml-pixverse-v5-i2v',
  'aiml-pixverse-v5-transition',
  // AI/ML API - Wan
  'aiml-wan-2.6-t2v',
  'aiml-wan-2.6-i2v',
  'aiml-wan-2.6-r2v',
  'aiml-wan-2.5-t2v',
  'aiml-wan-2.1-t2v',
  'aiml-wan-2.1-i2v',
  // AI/ML API - Seedance
  'aiml-seedance-pro-t2v',
  'aiml-seedance-pro-i2v',
  'aiml-seedance-lite-t2v',
  'aiml-seedance-lite-i2v',
  'aiml-omnihuman-1.5',
  'aiml-omnihuman',
  // AI/ML API - Altri
  'aiml-krea-wan-14b-t2v',
  'aiml-krea-wan-14b-v2v',
  'aiml-kandinsky5-t2v',
  'aiml-kandinsky5-distill-t2v',
  'aiml-veed-fabric-1.0',
  'aiml-veed-fabric-1.0-fast',
  // PiAPI
  'piapi-kling-2.6',
  'piapi-kling-2.5',
  'piapi-kling-2.1',
  'piapi-hailuo',
  'piapi-luma',
  'piapi-wan',
  'piapi-hunyuan',
  'piapi-skyreels',
  'piapi-framepack',
  'piapi-veo3',
  'piapi-sora2',
  // Freepik
  'freepik',
  // Vidu
  'vidu-q3-pro-t2v',
  'vidu-q3-pro-i2v',
  'vidu-q3-turbo-t2v',
  'vidu-q3-turbo-i2v',
  'vidu-q2-t2v',
  'vidu-q2-i2v',
  'vidu-q1-t2v',
  'vidu-q1-i2v',
];
